---
name: Examples
on:
  push:
    branches:
      - main
jobs:
  flakes:
    name: Flakes
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-13 # X64
          - macos-latest # ARM64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Lix
        uses: fabrictest/action-lix-quick-install@adf607f89b402b54025ff0a3b459be95559caa72 # v7.1.0
      - name: Print Lix version
        run: nix-build -v --version
      - name: Set up Nix binary cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
        with:
          use-flakehub: false
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build flake
        run: nix build ./examples/flakes
      - name: Print `hello, world` message
        run: ./result/bin/hello
